[package]
name = "simplicity-comparison-runner"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
simplicityhl = { git = "https://github.com/BlockstreamResearch/SimplicityHL", rev = "f3fa882e77c221e96e10acde9f0e46e68e69930f" }
simplicity-lang = { version = "=0.8.0", features = ["test-utils"] }
serde_json = "1"

[[bin]]
name = "simplicity-comparison-runner"
path = "runner.rs"
